# Generated by Django 4.0.4 on 2022-08-24 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(blank=True, choices=[('english', 'English'), ('gujrati', 'Gujrati')], max_length=270, null=True)),
                ('online', models.BooleanField(blank=True, default=False, null=True, verbose_name='Online')),
                ('offline', models.BooleanField(blank=True, default=False, null=True, verbose_name='Offline')),
                ('phone', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
