# Generated by Django 4.0.4 on 2022-08-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_signupmodel_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
