# Generated by Django 4.0.4 on 2022-08-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_signupmodel_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='upload',
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
