# Generated by Django 4.0.4 on 2022-08-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_signupmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='study',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], max_length=270, null=True),
        ),
    ]
