# Generated by Django 4.0.4 on 2022-08-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_signupmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='image',
            field=models.ImageField(default='media/ganpati.jpg', upload_to='media'),
        ),
    ]
