# Generated by Django 4.0.4 on 2022-08-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_alter_signupmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='study',
        ),
    ]
