# Generated by Django 4.0.4 on 2022-08-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_remove_signupmodel_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='image',
        ),
    ]
