# Generated by Django 4.0.4 on 2022-08-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_remove_signupmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='offline',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='online',
        ),
    ]
