# Generated by Django 4.0.4 on 2022-08-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_remove_signupmodel_offline_remove_signupmodel_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='image',
            field=models.ImageField(default='media/ganpati.jpg', upload_to='media'),
        ),
    ]
