# Generated by Django 4.0.4 on 2022-08-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_signupmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='image',
            field=models.ImageField(default='media/ganpati.jpg', unique=True, upload_to='media'),
        ),
    ]
