# Generated by Django 4.0.4 on 2022-08-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='study',
            field=models.CharField(blank=True, choices=[('online', 'online'), ('offline', 'offline')], max_length=270, null=True),
        ),
    ]
