# Generated by Django 4.0.4 on 2022-08-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_signupmodel_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='study',
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='offline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
