# Generated by Django 4.0.4 on 2022-08-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_remove_signupmodel_study_signupmodel_offline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='offline',
            field=models.BooleanField(default=False),
        ),
    ]
