# Generated by Django 4.0.4 on 2022-08-25 09:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_alter_signupmodel_offline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupmodel',
            name='offline',
        ),
        migrations.RemoveField(
            model_name='signupmodel',
            name='online',
        ),
        migrations.AddField(
            model_name='signupmodel',
            name='study',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('online', 'online'), ('offline', 'offline')], max_length=14, null=True),
        ),
    ]
