# Generated by Django 4.0.4 on 2022-08-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_remove_signupmodel_offline_remove_signupmodel_online_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupmodel',
            name='study',
            field=models.CharField(default='', max_length=270),
        ),
    ]
