# Generated by Django 4.0.4 on 2022-08-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_alter_signupmodel_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupmodel',
            name='video',
            field=models.FileField(default=' ', upload_to='video'),
        ),
    ]
